/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.99
 * Generated at: 2024-04-23 00:08:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.pages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Admin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("   <head>\n");
      out.write("      <meta charset=\"UTF-8\" />\n");
      out.write("      <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\" />\n");
      out.write("      <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\n");
      out.write("      <title>Admin Dashboard</title>\n");
      out.write("      <link\n");
      out.write("         href=\"https://fonts.googleapis.com/icon?family=Material+Icons+Sharp\"\n");
      out.write("         rel=\"stylesheet\" />\n");
      out.write("      <link rel=\"stylesheet\"\n");
      out.write("         href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/AdminHome.css\" />\n");
      out.write("   </head>\n");
      out.write("   <body>\n");
      out.write("      <div class=\"container\">\n");
      out.write("         <aside>\n");
      out.write("            <div class=\"top\">\n");
      out.write("               <div class=\"logo\">\n");
      out.write("                  <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/Images/logo.png\"\n");
      out.write("                     alt=\"\" />\n");
      out.write("                  <h2 class=\"text-muted\">PixlePrinters</h2>\n");
      out.write("               </div>\n");
      out.write("               <div class=\"close\" id=\"btn-close\">\n");
      out.write("                  <span class=\"material-icons-sharp\"> close </span>\n");
      out.write("               </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"sidebar\">\n");
      out.write("               <a href=\"#\">\n");
      out.write("                  <span class=\"material-icons-sharp\">\n");
      out.write("                  dashboard </span>\n");
      out.write("                  <h3>Dashboard</h3>\n");
      out.write("               </a>\n");
      out.write("               <a href=\"#\" class=\"actived\">\n");
      out.write("                  <span class=\"material-icons-sharp\">\n");
      out.write("                  person_outline </span>\n");
      out.write("                  <h3>Customers</h3>\n");
      out.write("               </a>\n");
      out.write("               <a href=\"#\">\n");
      out.write("                  <span class=\"material-icons-sharp\">\n");
      out.write("                  receipt_long </span>\n");
      out.write("                  <h3>Orders</h3>\n");
      out.write("               </a>\n");
      out.write("               <a href=\"#\">\n");
      out.write("                  <span class=\"material-icons-sharp\">\n");
      out.write("                  insights </span>\n");
      out.write("                  <h3>Analytics</h3>\n");
      out.write("               </a>\n");
      out.write("               <a href=\"#\">\n");
      out.write("                  <span class=\"material-icons-sharp\">\n");
      out.write("                  mail_outline </span>\n");
      out.write("                  <h3>Messagers</h3>\n");
      out.write("                  <span class=\"message-count\">27</span> <!--yo chain ni messafe counter ho haii-->\n");
      out.write("               </a>\n");
      out.write("               <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/AddProductServlet\">\n");
      out.write("                  <span class=\"material-icons-sharp\">\n");
      out.write("                  inventory </span>\n");
      out.write("                  <h3>Products</h3>\n");
      out.write("               </a>\n");
      out.write("               <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/AddProductServlet\">\n");
      out.write("                  <span class=\"material-icons-sharp\"> add </span>\n");
      out.write("                  <h3>Add Product</h3>\n");
      out.write("               </a>\n");
      out.write("               <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/pages/AddAdmin.jsp\">\n");
      out.write("                  <span class=\"material-icons-sharp\"> add </span>\n");
      out.write("                  <h3>Add Admin</h3>\n");
      out.write("                  </a>\n");
      out.write("                <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/AddBrand\">\n");
      out.write("                  <span class=\"material-icons-sharp\"> add </span>\n");
      out.write("                  <h3>Add Brand</h3>\n");
      out.write("                  </a>  \n");
      out.write("               <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/LogoutServlet\">\n");
      out.write("                  <span class=\"material-icons-sharp\"> logout </span>\n");
      out.write("                  <h3>Logoutt</h3>\n");
      out.write("               </a>\n");
      out.write("            </div>\n");
      out.write("         </aside>\n");
      out.write("         <main>\n");
      out.write("            <h1>Dashboard</h1>\n");
      out.write("            <div class=\"date\">\n");
      out.write("               <input type=\"date\" />\n");
      out.write("            </div>\n");
      out.write("            <div class=\"insights\">\n");
      out.write("               <div class=\"sales\">\n");
      out.write("                  <span class=\"material-icons-sharp\">analytics</span>\n");
      out.write("                  <div class=\"middle\">\n");
      out.write("                     <div class=\"left\">\n");
      out.write("                        <h3>Total Sales</h3>\n");
      out.write("                        <h1>$25,024</h1>\n");
      out.write("                     </div>\n");
      out.write("                     <div class=\"progress\">\n");
      out.write("                        <svg>\n");
      out.write("                           <circle cx=\"38\" cy=\"38\" r=\"36\"\n");
      out.write("                              stroke-dashoffset=\"42.56\" />\n");
      out.write("                        </svg>\n");
      out.write("                        <div class=\"number\">\n");
      out.write("                           <p>81%</p>\n");
      out.write("                        </div>\n");
      out.write("                     </div>\n");
      out.write("                  </div>\n");
      out.write("                  <small class=\"text-muted\">Last 24 Hours</small>\n");
      out.write("               </div>\n");
      out.write("               <!---------  END OF SALES   --------->\n");
      out.write("               <div class=\"expenses\">\n");
      out.write("                  <span class=\"material-icons-sharp\">bar_chart</span>\n");
      out.write("                  <div class=\"middle\">\n");
      out.write("                     <div class=\"left\">\n");
      out.write("                        <h3>Total Expenses</h3>\n");
      out.write("                        <h1>$27,174</h1>\n");
      out.write("                     </div>\n");
      out.write("                     <div class=\"progress\">\n");
      out.write("                        <svg>\n");
      out.write("                           <circle cx=\"38\" cy=\"38\" r=\"36\"\n");
      out.write("                              stroke-dashoffset=\"85\" />\n");
      out.write("                        </svg>\n");
      out.write("                        <div class=\"number\">\n");
      out.write("                           <p>62%</p>\n");
      out.write("                        </div>\n");
      out.write("                     </div>\n");
      out.write("                  </div>\n");
      out.write("                  <small class=\"text-muted\">Last 24 Hours</small>\n");
      out.write("               </div>\n");
      out.write("               <!---------  END OF EXPENSES   --------->\n");
      out.write("               <div class=\"income\">\n");
      out.write("                  <span class=\"material-icons-sharp\">stacked_line_chart</span>\n");
      out.write("                  <div class=\"middle\">\n");
      out.write("                     <div class=\"left\">\n");
      out.write("                        <h3>Total Income</h3>\n");
      out.write("                        <h1>$11,270</h1>\n");
      out.write("                     </div>\n");
      out.write("                     <div class=\"progress\">\n");
      out.write("                        <svg>\n");
      out.write("                           <circle cx=\"38\" cy=\"38\" r=\"36\"\n");
      out.write("                              stroke-dashoffset=\"125.44\" />\n");
      out.write("                        </svg>\n");
      out.write("                        <div class=\"number\">\n");
      out.write("                           <p>44%</p>\n");
      out.write("                        </div>\n");
      out.write("                     </div>\n");
      out.write("                  </div>\n");
      out.write("                  <small class=\"text-muted\">Last 24 Hours</small>\n");
      out.write("               </div>\n");
      out.write("               <!---------  END OF INCOME   --------->\n");
      out.write("            </div>\n");
      out.write("            <!---------  END OF INSIGHTS   --------->\n");
      out.write("            <div class=\"recent-orders\">\n");
      out.write("               <h2>Recent Orders</h2>\n");
      out.write("               <table>\n");
      out.write("                  <thead>\n");
      out.write("                     <tr>\n");
      out.write("                        <th>Product Name</th>\n");
      out.write("                        <th>Product Number</th>\n");
      out.write("                        <th>Payment</th>\n");
      out.write("                        <th>Status</th>\n");
      out.write("                        <th></th>\n");
      out.write("                     </tr>\n");
      out.write("                  </thead>\n");
      out.write("                  <tbody>\n");
      out.write("                     <tr>\n");
      out.write("                        <td>Iphone 12</td>\n");
      out.write("                        <td>23242526</td>\n");
      out.write("                        <td>Due</td>\n");
      out.write("                        <td class=\"warning\">Pending</td>\n");
      out.write("                        <td class=\"primary\">Details</td>\n");
      out.write("                     </tr>\n");
      out.write("                     <tr>\n");
      out.write("                        <td>Iphone 12</td>\n");
      out.write("                        <td>23242526</td>\n");
      out.write("                        <td>Due</td>\n");
      out.write("                        <td class=\"warning\">Pending</td>\n");
      out.write("                        <td class=\"primary\">Details</td>\n");
      out.write("                     </tr>\n");
      out.write("                  </tbody>\n");
      out.write("               </table>\n");
      out.write("               <a href=\"#\">Show More</a>\n");
      out.write("            </div>\n");
      out.write("            <!---------  END OF RECENT ORDER   --------->\n");
      out.write("         </main>\n");
      out.write("         <!---------  END OF MAIN   --------->\n");
      out.write("         <div class=\"right\">\n");
      out.write("            <div class=\"top\">\n");
      out.write("               <button id=\"btn-menu\">\n");
      out.write("               <span class=\"material-icons-sharp\"> menu </span>\n");
      out.write("               </button>\n");
      out.write("               <div class=\"theme-toggler\">\n");
      out.write("                  <span class=\"material-icons-sharp actived\"> light_mode </span> <span\n");
      out.write("                     class=\"material-icons-sharp\"> dark_mode </span>\n");
      out.write("               </div>\n");
      out.write("               <div class=\"profile\">\n");
      out.write("                  <div class=\"info\">\n");
      out.write("                     <p>\n");
      out.write("                        ");
 String username = (String) request.getSession().getAttribute("username"); 
      out.write("\n");
      out.write("                        ");
 if (username != null) { 
      out.write("\n");
      out.write("                        Hey, <b>");
      out.print( username );
      out.write("</b>\n");
      out.write("                        ");
 } 
      out.write("	\n");
      out.write("                     </p>\n");
      out.write("                     <div class=\"text-muted\">Admin</div>\n");
      out.write("                  </div>\n");
      out.write("                  <div class=\"profile-photo\">\n");
      out.write("                     <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/Uploads/ProfilePicture/Wanem1.png\"alt=\"Admin\"/>\n");
      out.write("                  </div>\n");
      out.write("               </div>\n");
      out.write("            </div>\n");
      out.write("            <!---------  END OF TOP   --------->\n");
      out.write("            <div class=\"recent-updates\">\n");
      out.write("               <h2>Recent Updates</h2>\n");
      out.write("               <div class=\"updates\">\n");
      out.write("                  <div class=\"update\">\n");
      out.write("                     <div class=\"profile-photo\">\n");
      out.write("                        <img src=\"./images/001.png\" alt=\"\" />\n");
      out.write("                     </div>\n");
      out.write("                     <div class=\"message\">\n");
      out.write("                        <p>\n");
      out.write("                           <b>Ramuh Lino</b> received his order of Night lion tech GPS\n");
      out.write("                           drobe.\n");
      out.write("                        </p>\n");
      out.write("                        <small>3 Minutes Ago</small>\n");
      out.write("                     </div>\n");
      out.write("                  </div>\n");
      out.write("                  <div class=\"update\">\n");
      out.write("                     <div class=\"profile-photo\">\n");
      out.write("                        <img src=\"./images/002.jpg\" alt=\"\" />\n");
      out.write("                     </div>\n");
      out.write("                     <div class=\"message\">\n");
      out.write("                        <p>\n");
      out.write("                           <b>Ramuh Lino</b> received his order of Night lion tech GPS\n");
      out.write("                           drobe.\n");
      out.write("                        </p>\n");
      out.write("                        <small>3 Minutes Ago</small>\n");
      out.write("                     </div>\n");
      out.write("                  </div>\n");
      out.write("               </div>\n");
      out.write("            </div>\n");
      out.write("            <!---------  END OF RECENT-UPDATES  --------->\n");
      out.write("            <div class=\"sales-analytics\">\n");
      out.write("               <h2>Sales Analytics</h2>\n");
      out.write("               <div class=\"item online\">\n");
      out.write("                  <div class=\"icon\">\n");
      out.write("                     <span class=\"material-icons-sharp\"> shopping_cart </span>\n");
      out.write("                  </div>\n");
      out.write("                  <div class=\"right\">\n");
      out.write("                     <div class=\"info\">\n");
      out.write("                        <h3>ONLINE ORDERS</h3>\n");
      out.write("                        <small class=\"text-muted\">Last 24 Hours</small>\n");
      out.write("                     </div>\n");
      out.write("                     <h5 class=\"success\">+39%</h5>\n");
      out.write("                     <h3>3480</h3>\n");
      out.write("                  </div>\n");
      out.write("               </div>\n");
      out.write("               <div class=\"item offline\">\n");
      out.write("                  <div class=\"icon\">\n");
      out.write("                     <span class=\"material-icons-sharp\"> local_mall </span>\n");
      out.write("                  </div>\n");
      out.write("                  <div class=\"right\">\n");
      out.write("                     <div class=\"info\">\n");
      out.write("                        <h3>OFFLINE ORDERS</h3>\n");
      out.write("                        <small class=\"text-muted\">Last 24 Hours</small>\n");
      out.write("                     </div>\n");
      out.write("                     <h5 class=\"warning\">+23%</h5>\n");
      out.write("                     <h3>1380</h3>\n");
      out.write("                  </div>\n");
      out.write("               </div>\n");
      out.write("               <div class=\"item customers\">\n");
      out.write("                  <div class=\"icon\">\n");
      out.write("                     <span class=\"material-icons-sharp\"> person </span>\n");
      out.write("                  </div>\n");
      out.write("                  <div class=\"right\">\n");
      out.write("                     <div class=\"info\">\n");
      out.write("                        <h3>NEW CUSTOMERS</h3>\n");
      out.write("                        <small class=\"text-muted\">Last 24 Hours</small>\n");
      out.write("                     </div>\n");
      out.write("                     <h5 class=\"success\">+27%</h5>\n");
      out.write("                     <h3>1380</h3>\n");
      out.write("                  </div>\n");
      out.write("               </div>\n");
      out.write("               <div class=\"item add-product\">\n");
      out.write("                  <span class=\"material-icons-sharp\"> add </span>\n");
      out.write("                  <h3>Add Product</h3>\n");
      out.write("               </div>\n");
      out.write("            </div>\n");
      out.write("         </div>\n");
      out.write("      </div>\n");
      out.write("      <span class=\"aside-overview\"></span>\n");
      out.write("      <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/AdminHome.js\"></script>\n");
      out.write("   </body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
